name: Flask App CI

on:
  push:
    branches:
      - master

jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Flask App
        run: |
          python -m flask run
        env:
          FLASK_APP: src/app.py
      
      - name: Stop Flask App
        run: |
          pkill -f 'flask run'      
      